### ISSUE TITLE
Optional is not a Monad?

### ISSUE THREAD

**Issue by hoddez** [JaviSoto/Blog-Posts#2]
Nice article Javi. I just came across a scenario where I would like to have a flatMap on optional, and I realized there isn't one. 

Therefore, in the swift standard library Optional is current a Functor but not a Monad right? 

I'm thinking this might be a great use-case to point out for a practical benefit having a monad.

You already encourage people to come up with their own flatMap for Optional in your article, which is great, but maybe you could also mention that there actually is no flatMap for optional, and you could use an extension to turn Optional into a Monad using your own implementation of flatMap.

Here is a trivial example of when you may want a flatMap in optional. The nesting comes when you are using an Optional return value within your map function.

``` swift
func squareRoot(number: Int) -> Int? {
    let root = Int(sqrt(Float(number)))
    return root * root == number ? root : nil
}

let optionalInput: Int? = 4

let optionalOutput = optionalInput.map { squareRoot($0) }

println (optionalOutput)
//=> Optional(Optional(2))

if let unwrappedOutput = optionalOutput {
    println(unwrappedOutput)
    //=> Optional(2)
}
```

**Comment by JaviSoto** [comment]
Hi Tom! Thanks for reading it and commenting :D

You're absolutely right: Optional, the way it's currently implemented in the Swift std-lib, doesn't meet the requirements to be called a Monad (although we can say that the type itself is monadic, since we can easily implement the flatMap function with very clear behavior).

I had a conversation recently on Twitter about this, and it seems that the biggest blocker for Apple to implement this function is actually naming it! What would you call it? `flatMap` is a kind of obscure name. The only thing it has going for it is that it's the name used in other languages, but Haskell uses `bind` (another arbitrary name).

> You already encourage people to come up with their own flatMap for Optional in your article

I guess you mean `Result` here?

But yeah, you're right, I could've showed how to turn Optional into a monad. However, if the article is clear enough, one should have enough tools to know how to do so :)
And you're absolutely right that `flatMap` in Optional would be very useful. I find myself implementing it over and over every time I'm playing with any Swift code in a Playground.

**Comment by hoddez** [comment]
Ah interesting. I guess that means that nothing in swift std-lib is a monad yet.

The article is great as is. I just liked the extra info and wasn't sure if I had missed something on optional that would make it a monad.

**Comment by JaviSoto** [comment]
No, this is great feedback! It may help for me to come up with a new post :)

Let me know if you have any more questions! Happy to help.
